public enum EventType
{
    ShowMenu,
    HideMenu,
    ShowText,
    ShowTask,
    ShowWechat,
    EventStart,
    EventFinish,
    // UpdateTask,
    ActionStart,
    WechatStart,
    WechatFinish,
    WebStart,
    WebFinish,
    DoorOpen,
    ShowQuestion,
    HideQuestion,
    ShowInteraction,
    HideInteraction,
    //UpdateQuestion,
    CreateOptions,
    TestBroadcast,
}
